name: Build and Push from dev to staging and from staging to Production
on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build_and_push_dev_to_staging:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start and stop Python script
        run: |
          python main.py &               
          sleep 5s                      
          pkill -f "python main.py"      
      - name: Run Tests
        run: | 
          python test.py
          
      - name: Push Dev to staging
        run: |
          git config user.email "artitambe26@gmail.com"
          git config user.name "Arti Tambe"
          git fetch origin 
          git checkout staging
          git merge --allow-unrelated-histories -X theirs dev
          git push --force origin staging
        

  raise_pull_request:
    runs-on: ubuntu-latest

    needs: build_and_push_dev_to_staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: create pull request
        # run: gh pr create -B main -H staging --title 'Merge staging into main' --body 'Created by Github action' hello
        run: |
          git pull  
          git branch
          git checkout staging
          gh pr create --base main --title 'Merge staging into main' --body 'Created by Github action' --reviewer artitambe2602
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
     
